@startuml
[*] -> Ready

state Check <<choice>>
Ready -> Check : start()
Check -> Error : [water == 0]
Check -> Preparation : [water > 0]
Error -> Ready : refill()

state Preparation {

  [*] -> Grind

  state fork1 <<fork>>
  Grind -> fork1
  fork1 -> BrewEspresso
  fork1 -> FrothMilk

  state join1 <<join>>
  BrewEspresso -> join1
  FrothMilk -> join1
}

join1 -> Serve
Serve -> Ready : drink()

Preparation -> Pause : stop()
Pause -> Preparation[H] : resume()

@enduml